camera_front.image_raw.enable_pub_plugins:
- image_transport/compressedDepth
- image_transport/compressed
- image_transport/raw
- image_transport/theora
camera_front.image_raw.format: jpeg
camera_front.image_raw.jpeg_quality: 50
camera_front.image_raw.png_level: 3
camera_front.image_raw.tiff.res_unit: inch
camera_front.image_raw.tiff.xdpi: -1
camera_front.image_raw.tiff.ydpi: -1
camera_front_left.image_raw.enable_pub_plugins:
- image_transport/compressedDepth
- image_transport/compressed
- image_transport/raw
- image_transport/theora
camera_front_left.image_raw.format: jpeg
camera_front_left.image_raw.jpeg_quality: 50
camera_front_left.image_raw.png_level: 3
camera_front_left.image_raw.tiff.res_unit: inch
camera_front_left.image_raw.tiff.xdpi: -1
camera_front_left.image_raw.tiff.ydpi: -1
camera_front_right.image_raw.enable_pub_plugins:
- image_transport/compressedDepth
- image_transport/compressed
- image_transport/raw
- image_transport/theora
camera_front_right.image_raw.format: jpeg
camera_front_right.image_raw.jpeg_quality: 50
camera_front_right.image_raw.png_level: 3
camera_front_right.image_raw.tiff.res_unit: inch
camera_front_right.image_raw.tiff.xdpi: -1
camera_front_right.image_raw.tiff.ydpi: -1
frame_id_front: front_camera_frame
frame_id_left: left_camera_frame
frame_id_right: right_camera_frame
front_image_pattern: front*.jpg
image_directory: /home/david/Documents/Datasets/imagenes_luis/02
jpeg_quality: 10
left_image_pattern: front_left*.jpg
loop_playback: true
publish_rate: 10.0
qos_overrides./parameter_events.publisher.depth: 1000
qos_overrides./parameter_events.publisher.durability: volatile
qos_overrides./parameter_events.publisher.history: keep_last
qos_overrides./parameter_events.publisher.reliability: reliable
right_image_pattern: front_right*.jpg
use_sim_time: false
