#nombre_mapa: arganda_HD_modificado_2 # Si es dataset de nuscenes no se carga así. Se lee con unos ficheros.
#nombre_mapa: arganda_rotonda_peatones
nombre_mapa: CAR
#nombre_mapa: CAR_margen_seguridad_04


#################################################### COCHE_AMARILLO

# nombre_mapa: arganda_HD
arganda_HD_path_mapa_ruta: arganda_HD/
arganda_HD_NC_X_route_map: 22369 # Columnas (Juan lo hace al reves)
arganda_HD_NC_Y_route_map: 12867 # Filas (Juan lo hace al reves)
arganda_HD_UTM_origen_mapa_x: 460125.916
arganda_HD_UTM_origen_mapa_y: 4461704.17
arganda_HD_UTM_origen_mapa_heading: 0 
arganda_HD_lado_celda: 0.2


arganda_HD_modificado_path_mapa_ruta: arganda_HD_modificado/
arganda_HD_modificado_NC_X_route_map: 22369 # Columnas (Juan lo hace al reves)
arganda_HD_modificado_NC_Y_route_map: 12867 # Filas (Juan lo hace al reves)
arganda_HD_modificado_UTM_origen_mapa_x: 460125.916
arganda_HD_modificado_UTM_origen_mapa_y: 4461704.17
arganda_HD_modificado_UTM_origen_mapa_heading: 0 
arganda_HD_modificado_lado_celda: 0.2


arganda_HD_modificado_2_path_mapa_ruta: arganda_HD_modificado_2/
arganda_HD_modificado_2_NC_X_route_map: 10500 # Columnas (Juan lo hace al reves)
arganda_HD_modificado_2_NC_Y_route_map: 8000 # Filas (Juan lo hace al reves)
arganda_HD_modificado_2_UTM_origen_mapa_x: 460125.916
arganda_HD_modificado_2_UTM_origen_mapa_y: 4461704.17
arganda_HD_modificado_2_UTM_origen_mapa_heading: 0 
arganda_HD_modificado_2_lado_celda: 0.2

# nombre_mapa: arganda_rotonda_peatones
arganda_rotonda_peatones_path_mapa_ruta: arganda_rotonda_peatones/
arganda_rotonda_peatones_NC_X_route_map: 1103 # Columnas (Juan lo hace al reves)
arganda_rotonda_peatones_NC_Y_route_map: 989 # Filas (Juan lo hace al reves)
arganda_rotonda_peatones_UTM_origen_mapa_x: 461501.603
arganda_rotonda_peatones_UTM_origen_mapa_y: 4461525
arganda_rotonda_peatones_UTM_origen_mapa_heading: 0 
arganda_rotonda_peatones_lado_celda: 0.2


# nombre_mapa: arganda
arganda_path_mapa_ruta: arganda/
arganda_NC_X_route_map: 20213 # Columnas (Juan lo hace al reves)
arganda_NC_Y_route_map: 12471 # Filas (Juan lo hace al reves)
arganda_UTM_origen_mapa_x: 459979.523
arganda_UTM_origen_mapa_y: 4481452.65
arganda_UTM_origen_mapa_heading: 0 
arganda_lado_celda: 0.2

# nombre_mapa: arganda_reducido
arganda_reducido_path_mapa_ruta: arganda_reducido/
arganda_reducido_NC_X_route_map: 12000 # Columnas (Juan lo hace al reves)
arganda_reducido_NC_Y_route_map: 9000 # Filas (Juan lo hace al reves)
arganda_reducido_UTM_origen_mapa_x: 459979.523
arganda_reducido_UTM_origen_mapa_y: 4481452.65
arganda_reducido_UTM_origen_mapa_heading: 0 
arganda_reducido_lado_celda: 0.2

# nombre_mapa: CAR
CAR_path_mapa_ruta: CAR/
CAR_NC_X_route_map: 1370 # Columnas (Juan lo hace al reves)
CAR_NC_Y_route_map: 620 # Filas (Juan lo hace al reves)
CAR_UTM_origen_mapa_x: 459069.486
#CAR_UTM_origen_mapa_y: 4482480.05 mal 
CAR_UTM_origen_mapa_y: 4462480.05
CAR_UTM_origen_mapa_heading: 0 
CAR_lado_celda: 0.2

CAR_margen_seguridad_04_path_mapa_ruta: CAR_margen_seguridad_04/
CAR_margen_seguridad_04_NC_X_route_map: 1370 # Columnas (Juan lo hace al reves)
CAR_margen_seguridad_04_NC_Y_route_map: 620 # Filas (Juan lo hace al reves)
CAR_margen_seguridad_04_UTM_origen_mapa_x: 459069.486
CAR_margen_seguridad_04_UTM_origen_mapa_y: 4462480.05
CAR_margen_seguridad_04_UTM_origen_mapa_heading: 0 
CAR_margen_seguridad_04_lado_celda: 0.2

# nombre_mapa: idiada
idiada_path_mapa_ruta: idiada/
idiada_NC_X_route_map: 6567 # Columnas (Juan lo hace al reves)
idiada_NC_Y_route_map: 1648 # Filas (Juan lo hace al reves)
idiada_UTM_origen_mapa_x: 376511.165
idiada_UTM_origen_mapa_y: 4568963.22
idiada_UTM_origen_mapa_heading: 0 
idiada_lado_celda: 0.2

# nombre_mapa: idiada_2
idiada_2_path_mapa_ruta: idiada_2/
idiada_2_NC_X_route_map: 6567 # Columnas (Juan lo hace al reves)
idiada_2_NC_Y_route_map: 1648 # Filas (Juan lo hace al reves)
idiada_2_UTM_origen_mapa_x: 376511.165
idiada_2_UTM_origen_mapa_y: 4568963.22
idiada_2_UTM_origen_mapa_heading: 0 
idiada_2_lado_celda: 0.2

# nombre_mapa: idiada_adelantamiento
idiada_adelantamiento_HD_path_mapa_ruta: idiada_adelantamiento/
idiada_adelantamiento_NC_X_route_map: 6567 # Columnas (Juan lo hace al reves)
idiada_adelantamiento_NC_Y_route_map: 1417 # Filas (Juan lo hace al reves)
idiada_adelantamiento_UTM_origen_mapa_x: 376511.165
idiada_adelantamiento_UTM_origen_mapa_y: 4569009.07
idiada_adelantamiento_UTM_origen_mapa_heading: 0 
idiada_adelantamiento_lado_celda: 0.2

# nombre_mapa: idiada_obras
idiada_obras_HD_path_mapa_ruta: idiada_obras/
idiada_obras_NC_X_route_map: 6567 # Columnas (Juan lo hace al reves)
idiada_obras_NC_Y_route_map: 1417 # Filas (Juan lo hace al reves)
idiada_obras_UTM_origen_mapa_x: 376511.165
idiada_obras_UTM_origen_mapa_y: 4569009.07
idiada_obras_UTM_origen_mapa_heading: 0 
idiada_obras_lado_celda: 0.2

# nombre_mapa: idiada_oficinas
idiada_oficinas_HD_path_mapa_ruta: idiada_oficinas/
idiada_oficinas_NC_X_route_map: 2080 # Columnas (Juan lo hace al reves)
idiada_oficinas_NC_Y_route_map: 706 # Filas (Juan lo hace al reves)
idiada_oficinas_UTM_origen_mapa_x: 376347.337
idiada_oficinas_UTM_origen_mapa_y: 4569242.0
idiada_oficinas_UTM_origen_mapa_heading: 0 
idiada_oficinas_lado_celda: 0.2




#################################3 Parámetros
type_off_road: 0
type_carretera: 1





