# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    config_on_startup: false

    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyGPS0
    frame_id: gps
    uart1:
      baudrate: 460800
    

 
